name: Build
on:
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm  ci
      - name: Linting
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm build
